<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MyFinder.Core\MyFinder.Core.csproj" />
    <ProjectReference Include="..\MyFinder.Database\MyFinder.Database.csproj" />
    <ProjectReference Include="..\MyFinder.Models\MyFinder.Models.csproj" />
  </ItemGroup>
</Project>
