<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>
    <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
    <Platforms>x64</Platforms>
    <Platform>x64</Platform>
    <RootNamespace>MyFinder.UI</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <UseWinUI>true</UseWinUI>
    <WindowsPackageType>None</WindowsPackageType>
    <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
    <SelfContained>true</SelfContained>
    <EnableMsixTooling>false</EnableMsixTooling>
    <ApplicationIcon>MyFinder.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.WindowsDesktop.App.WindowsForms" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.6.240923002" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.10" />
    <PackageReference Include="H.NotifyIcon.WinUI" Version="2.0.124" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="MyFinder.ico" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MyFinder.Backup\MyFinder.Backup.csproj" />
    <ProjectReference Include="..\MyFinder.Core\MyFinder.Core.csproj" />
    <ProjectReference Include="..\MyFinder.Database\MyFinder.Database.csproj" />
    <ProjectReference Include="..\MyFinder.Index\MyFinder.Index.csproj" />
    <ProjectReference Include="..\MyFinder.Models\MyFinder.Models.csproj" />
    <ProjectReference Include="..\MyFinder.Search\MyFinder.Search.csproj" />
    <ProjectReference Include="..\MyFinder.Services\MyFinder.Services.csproj" />
  </ItemGroup>
</Project>